/**
 * Equipment model database — ported from mobile app's lib/equipment/models/.
 * Model strings only (no specs). For each brand list, the caller should append
 * "Other" to surface a free-text fallback.
 *
 * Coverage: ~3,100 model entries across clubs (per-subcategory), shafts,
 * grips, balls, clothing, hats, sunglasses, gloves, shoes, and the main
 * accessory subcategories. Training Aids and Trolleys are not yet broken
 * down by brand in mobile (grouped by sub-type instead), so they fall back
 * to free-text — see questions.md.
 */


// ─────── Clubs: subcategory → brand → models[] ───────
const CLUBS: Record<string, Record<string, string[]>> = {
  "Drivers": {
    "TaylorMade": [
      "Qi35",
      "Qi35 Max Lite",
      "Qi10",
      "Qi10 Max",
      "Stealth 2",
      "Stealth",
      "SIM2",
      "SIM",
      "M5",
      "M6",
      "M3",
      "M4",
      "M1 2017",
      "M2 2017",
      "M1",
      "M2",
      "R15",
      "AeroBurner",
      "AeroBurner TP",
      "SLDR",
      "SLDR 430",
      "SLDR S",
      "JetSpeed",
      "RocketBallz Stage 2",
      "RocketBallz Stage 2 Tour",
      "R1",
      "R11S",
      "RocketBallz",
      "RocketBallz Tour",
      "RocketBallz Bonded",
      "Burner SuperFast 2.0",
      "R11",
      "R9 SuperTri",
      "R9 460",
      "R9 SuperDeep",
      "Burner SuperFast",
      "R9",
      "Burner",
      "Tour Burner",
      "r7 SuperQuad",
      "r7 CGB Max",
      "r7 460",
      "r7 Draw",
      "r7 Quad",
      "r7 425",
      "r5 Dual",
      "r510"
    ],
    "Callaway": [
      "Elyte",
      "Elyte Ti",
      "Paradym Ai Smoke",
      "Great Big Bertha",
      "Paradym",
      "Rogue ST",
      "Epic Speed",
      "Epic Max",
      "Big Bertha B21",
      "Mavrik",
      "Epic Flash",
      "Rogue",
      "Epic",
      "GBB Epic",
      "XR 16",
      "XR 16 Pro",
      "Big Bertha Fusion",
      "Big Bertha Alpha 816",
      "Big Bertha Alpha 816 Double Black Diamond",
      "XR",
      "XR Pro",
      "Big Bertha Alpha 815",
      "Big Bertha Alpha 815 Double Black Diamond",
      "Big Bertha",
      "Big Bertha Alpha",
      "Big Bertha V Series",
      "RAZR Fit Xtreme",
      "X Hot",
      "X Hot Pro",
      "FT Optiforce",
      "RAZR Fit",
      "RAZR X Black",
      "RAZR Hawk",
      "Diablo Octane Tour",
      "FT-iZ",
      "Diablo Edge",
      "Diablo Octane",
      "FT-i",
      "FT-9",
      "FT-5",
      "FT-3",
      "Big Bertha 460",
      "Big Bertha Titanium",
      "Big Bertha 454",
      "Fusion FT-3"
    ],
    "Titleist": [
      "GT1",
      "GT2",
      "GT3",
      "GT4",
      "TSR1",
      "TSR2",
      "TSR3",
      "TSR4",
      "TSi1",
      "TSi2",
      "TSi3",
      "TSi4",
      "TS1",
      "TS2",
      "TS3",
      "TS4",
      "917D2",
      "917D3",
      "915D2",
      "915D3",
      "915Dd",
      "913D2",
      "913D3",
      "910D2",
      "910D3",
      "909D2",
      "909D3",
      "907D1",
      "907D2",
      "905R",
      "905S",
      "905T"
    ],
    "Ping": [
      "G430 Max 10K",
      "G430 Max",
      "G430 LST",
      "G430 SFT",
      "G425 Max",
      "G425 LST",
      "G425 SFT",
      "G410 Plus",
      "G410 LST",
      "G410 SFT",
      "G400 Max",
      "G400 LST",
      "G400 SFT",
      "G400",
      "G",
      "i25",
      "G30",
      "G25",
      "i20",
      "Anser",
      "G20",
      "K15",
      "K15 SF Tec",
      "i15",
      "G15",
      "Rapture V2",
      "i10",
      "G10",
      "Rapture",
      "i5",
      "G5",
      "G2",
      "i3"
    ],
    "Cobra": [
      "Darkspeed",
      "Darkspeed X",
      "Aerojet",
      "LTDx",
      "Radspeed",
      "King Speedzone",
      "King F9 Speedback",
      "King F8",
      "King F7",
      "King LTD",
      "King F6",
      "King F6+",
      "Fly-Z",
      "Fly-Z+",
      "Bio Cell",
      "Bio Cell+",
      "Baffler XL",
      "AMP Cell",
      "AMP Cell Pro",
      "ZL Encore",
      "S3",
      "S3 Max",
      "ZL",
      "AMP",
      "S2",
      "S9-1",
      "L4V",
      "L5V",
      "Speed Pro",
      "Speed LD",
      "HS9",
      "SS 427",
      "COMP 454",
      "COMP 414",
      "SS 380",
      "SS 310",
      "J Speed",
      "King F-Max"
    ],
    "Mizuno": [
      "ST-Z 230",
      "ST-X 230",
      "ST-Max 230",
      "ST-G 220",
      "ST-Z 220",
      "ST-X 220",
      "ST-Z",
      "ST-X",
      "ST200",
      "ST190",
      "ST180",
      "JPX-900",
      "JPX-EZ",
      "JPX-850",
      "JPX-825",
      "JPX-800",
      "MP-630",
      "MP-600",
      "MX-700",
      "MP-FLI HI",
      "MX-560",
      "MX-500",
      "MP-460",
      "MP-001"
    ],
    "PXG": [
      "0211 (2024)",
      "Black Ops",
      "0311 GEN6",
      "0311 GEN5",
      "0211 (2022)",
      "0811 X+ Gen4",
      "0811 XF Gen3",
      "0811 X Gen2",
      "0811 XF Gen2",
      "0811 LX",
      "0811 Gen1",
      "0211"
    ],
    "Honma": [
      "TW767 D",
      "TW767 S",
      "TW757 D",
      "TW757 S",
      "GS",
      "TR21 Titanium",
      "BERES 09 (2-Star)",
      "BERES 09 (3-Star)",
      "BERES 09 (5-Star)",
      "BERES Nx",
      "BERES 08 (2-Star)",
      "BERES 08 (3-Star)",
      "BERES 07 (2-Star)",
      "BERES 07 (3-Star)",
      "BERES 06 (2-Star)",
      "BERES 06 (3-Star)",
      "TR20",
      "TW747",
      "TW737",
      "TW727 455",
      "TW727 460",
      "Be ZEAL 535",
      "S-07",
      "S-06"
    ],
    "Wilson": [
      "Dynapower Carbon",
      "Dynapower Titanium",
      "Dynapower LS",
      "D9",
      "Launch Pad 2",
      "Launch Pad",
      "D7",
      "D-300",
      "C-200",
      "D-200",
      "D-100",
      "Ultra",
      "Tour Velocity",
      "Deep Red",
      "Deep Red Max",
      "Pro Staff SGI"
    ],
    "Wilson Staff": [
      "Dynapower Carbon",
      "Dynapower LS",
      "Dynapower Titanium",
      "D9",
      "D7",
      "Launch Pad",
      "Launch Pad 2",
      "C-300",
      "D-300",
      "FG Tour V6",
      "FG Tour F5",
      "D-200",
      "D-100",
      "D-150",
      "FG Tour V4",
      "FG Tour V2"
    ],
    "Tour Edge": [
      "Exotics E725",
      "Exotics C725",
      "Exotics E725 Lite",
      "Exotics E724",
      "Exotics C724",
      "Hot Launch E524",
      "Hot Launch X524",
      "Hot Launch E525",
      "Hot Launch X525",
      "Exotics C723",
      "Exotics E723",
      "Exotics E722",
      "Exotics C722",
      "Hot Launch E521",
      "Hot Launch C521",
      "Hot Launch C522",
      "Hot Launch E522",
      "Exotics EXS 220",
      "Exotics EXS",
      "Exotics E8",
      "Exotics CB5",
      "Exotics CB4",
      "Exotics CB3",
      "Exotics XCG6",
      "Exotics XCG5",
      "Exotics XCG4",
      "Exotics XCG3",
      "Bazooka 470"
    ]
  },
  "Fairway Woods": {
    "TaylorMade": [
      "Qi35",
      "Qi10",
      "Stealth 2",
      "Stealth 2 Plus",
      "Stealth 2 HD",
      "Stealth",
      "SIM2",
      "SIM",
      "M5",
      "M6",
      "M3",
      "M4",
      "M1 2017",
      "M2 2017",
      "M1",
      "M2",
      "R15",
      "AeroBurner",
      "AeroBurner TP",
      "SLDR",
      "SLDR S",
      "JetSpeed",
      "RocketBallz Stage 2",
      "RocketBallz Stage 2 Tour",
      "R1",
      "R11S",
      "RocketBallz",
      "R11",
      "Burner SuperFast 2.0",
      "Burner SuperFast",
      "r9",
      "Burner",
      "Tour Burner",
      "r7 SuperQuad",
      "r7 Steel",
      "r7 Draw",
      "r7 TP",
      "r7 Quad",
      "r5",
      "r7 425",
      "r5 Dual",
      "Rescue Dual",
      "r9 SuperDeep"
    ],
    "Callaway": [
      "Elyte",
      "Paradym Ai Smoke",
      "Paradym",
      "Rogue ST",
      "Epic Speed",
      "Epic Max",
      "Mavrik",
      "Epic Flash",
      "Rogue",
      "Epic",
      "GBB Epic",
      "XR 16",
      "XR 16 Pro",
      "Great Big Bertha",
      "Big Bertha Alpha 816",
      "Steelhead XR",
      "XR",
      "XR Pro",
      "Big Bertha",
      "X2 Hot",
      "X2 Hot Pro",
      "RAZR Fit Xtreme",
      "X Hot",
      "X Hot Pro",
      "RAZR X",
      "RAZR Fit",
      "RAZR Hawk",
      "Diablo Octane",
      "Diablo Edge",
      "Big Bertha Diablo",
      "FT-i",
      "FT-9",
      "FT-5",
      "FT-3",
      "Fusion FT-3"
    ],
    "Titleist": [
      "GT2",
      "GT3",
      "GT4",
      "TSR2",
      "TSR3",
      "TSi2",
      "TSi3",
      "TS2",
      "TS3",
      "917F2",
      "917F3",
      "915F",
      "915Fd",
      "913F",
      "913Fd",
      "910F",
      "910Fd",
      "909F",
      "909F2",
      "907F",
      "906F2",
      "906F4",
      "905R",
      "905S",
      "905T",
      "904F",
      "975F",
      "980F",
      "TS4",
      "917F"
    ],
    "Ping": [
      "G430 Max",
      "G430 LST",
      "G430 SFT",
      "G425 Max",
      "G425 LST",
      "G425 SFT",
      "G410",
      "G400",
      "G400 SF Tec",
      "G",
      "G30",
      "i25",
      "G25",
      "i20",
      "G20",
      "K15",
      "i15",
      "G15",
      "Rapture V2",
      "i10",
      "G10",
      "Rapture",
      "G5",
      "i5",
      "G2"
    ],
    "Cobra": [
      "Darkspeed",
      "Aerojet",
      "LTDx",
      "Radspeed",
      "King Speedzone",
      "King F9",
      "King F8",
      "King F7",
      "King F6",
      "Fly-Z",
      "Fly-Z XL",
      "Baffler XL",
      "Bio Cell",
      "AMP Cell",
      "AMP",
      "ZL Encore",
      "S3",
      "S2",
      "S9-1",
      "Speed LD",
      "Speed Pro"
    ],
    "Mizuno": [
      "ST-Z 230",
      "ST-X 230",
      "ST-Z 220",
      "ST-X 220",
      "ST-X",
      "ST-Z",
      "ST200",
      "ST190",
      "CLK",
      "JPX-900",
      "JPX-850",
      "JPX-825",
      "MP-650",
      "JPX-800",
      "MX-700",
      "MX-560",
      "MP-600"
    ],
    "PXG": [
      "0211 (2024)",
      "Black Ops",
      "0311 GEN6",
      "0311 GEN5",
      "0317 X",
      "0341 X",
      "0317 Gen2",
      "0317 Gen3",
      "0211"
    ],
    "Honma": [
      "TW767",
      "TW757",
      "GS",
      "TR21 Titanium",
      "BERES 09 (2-Star)",
      "BERES 09 (3-Star)",
      "BERES Nx",
      "BERES 08 (2-Star)",
      "BERES 07 (2-Star)",
      "TW747",
      "TW737",
      "TW737 C",
      "TW727",
      "Be ZEAL 535",
      "S-07",
      "S-06"
    ],
    "Wilson": [
      "Dynapower",
      "D9",
      "Launch Pad 2",
      "D-300",
      "C-200",
      "D-200",
      "D-100",
      "Ultra",
      "Tour Velocity",
      "Deep Red",
      "Deep Red Max"
    ],
    "Wilson Staff": [
      "Dynapower",
      "D9",
      "Launch Pad",
      "Launch Pad 2",
      "FG Tour V6",
      "FG Tour F5",
      "D-300",
      "D-200",
      "D-100"
    ],
    "Tour Edge": [
      "Exotics E725",
      "Exotics C725",
      "Exotics E725 Lite",
      "Exotics E724",
      "Exotics C724",
      "Hot Launch E524",
      "Hot Launch E525",
      "Exotics C723",
      "Hot Launch C522",
      "Hot Launch E522",
      "Hot Launch C521",
      "Hot Launch E521",
      "Exotics E722",
      "Exotics EXS 220",
      "Exotics CBX 119",
      "Exotics E8",
      "Exotics CB5 Tour",
      "Exotics CB4 Tour",
      "Exotics XCG7",
      "Exotics XCG6",
      "Bazooka 470"
    ]
  },
  "Hybrids": {
    "TaylorMade": [
      "Qi35",
      "Qi10",
      "Stealth 2",
      "Stealth 2 Plus",
      "Stealth 2 HD",
      "Stealth",
      "SIM2",
      "SIM2 Max",
      "SIM",
      "SIM Max",
      "M5",
      "M6",
      "M3",
      "M4",
      "Gapr Lo/Mid/Hi",
      "M1 2017",
      "M2 2017",
      "M1",
      "M2",
      "AeroBurner",
      "AeroBurner TP",
      "R15",
      "SLDR",
      "SLDR S",
      "JetSpeed",
      "RocketBallz Stage 2",
      "RBZ Stage 2 Tour",
      "RocketBallz",
      "R11S",
      "R11",
      "Burner SuperFast 2.0",
      "Burner SuperFast",
      "R9 SuperTri",
      "R9",
      "Burner",
      "Rescue 09",
      "Rescue",
      "r7 SuperQuad",
      "Rescue TP",
      "Rescue Mid",
      "Rescue Dual",
      "Rescue Dual TP",
      "r9 TP"
    ],
    "Callaway": [
      "Elyte",
      "Paradym Ai Smoke",
      "Paradym",
      "Paradym Super Hybrid",
      "Rogue ST",
      "Epic Speed",
      "Epic Max",
      "Apex",
      "Mavrik",
      "Epic Flash",
      "Rogue",
      "Epic",
      "GBB Epic",
      "XR OS",
      "Big Bertha OS",
      "Steelhead XR",
      "XR",
      "Big Bertha",
      "X2 Hot",
      "X Hot",
      "RAZR X",
      "RAZR X HL",
      "Diablo Edge",
      "Big Bertha Diablo",
      "FT-i",
      "FT-9",
      "FT-5"
    ],
    "Titleist": [
      "GT1",
      "GT2",
      "GT3",
      "TSR",
      "TSi",
      "TS",
      "818 H1",
      "818 H2",
      "816 H1",
      "816 H2",
      "915H",
      "915Hd",
      "913H",
      "913Hd",
      "910H",
      "909H",
      "907H",
      "905R",
      "905T",
      "TS4",
      "TSR2"
    ],
    "Ping": [
      "G430",
      "G425",
      "G410",
      "G400",
      "G",
      "i25",
      "G30",
      "G25",
      "i20",
      "G20",
      "K15",
      "i15",
      "G15",
      "Rapture V2",
      "i10",
      "G10",
      "Rapture",
      "G5",
      "G2"
    ],
    "Cobra": [
      "Darkspeed",
      "Aerojet",
      "LTDx",
      "Radspeed",
      "King Speedzone",
      "King F9",
      "King F8",
      "King F7",
      "King F6",
      "Fly-Z",
      "Baffler XL",
      "Bio Cell",
      "AMP Cell",
      "AMP",
      "ZL Encore",
      "S3",
      "S2",
      "S9-1",
      "Speed LD",
      "King F-Max"
    ],
    "Mizuno": [
      "Pro Fli-Hi 241",
      "ST-Z 230",
      "ST-X 230",
      "ST-Z 220",
      "ST200",
      "ST190",
      "CLK",
      "JPX-900",
      "JPX-850",
      "MP-H5",
      "MP-H4",
      "JPX Fli-Hi",
      "CLK Fli-Hi",
      "MX-200",
      "MP-630 Fli-Hi"
    ],
    "PXG": [
      "0211 (2024)",
      "Black Ops",
      "0311 GEN6",
      "0311 GEN5",
      "0317 Gen3",
      "0317 Gen2",
      "0211"
    ],
    "Honma": [
      "TW767",
      "TW757",
      "GS",
      "TR21",
      "BERES 09",
      "BERES 07",
      "TW747",
      "TW737",
      "TW727",
      "Be ZEAL 535"
    ],
    "Wilson": [
      "Dynapower",
      "D9",
      "Launch Pad 2",
      "D-300",
      "D-200",
      "D-100",
      "Ultra",
      "Pro Staff SGI"
    ],
    "Wilson Staff": [
      "Dynapower",
      "D9",
      "Launch Pad",
      "Launch Pad 2",
      "FG Tour V6",
      "D-300",
      "D-200"
    ],
    "Tour Edge": [
      "Exotics E725",
      "Exotics E724",
      "Exotics C724",
      "Hot Launch E524",
      "Hot Launch E525",
      "Exotics C723",
      "Hot Launch C522",
      "Hot Launch E522",
      "Hot Launch C521",
      "Hot Launch E521",
      "Exotics EXS 220",
      "Exotics CBX 119",
      "Exotics E8",
      "Bazooka 470"
    ]
  },
  "Irons": {
    "TaylorMade": [
      "Qi",
      "Qi10",
      "P7MB 2023",
      "P7MC 2023",
      "P770 2023",
      "P790 2023",
      "Stealth",
      "Stealth HD",
      "P770 2021",
      "P790 2021",
      "SIM2 Max",
      "SIM2 Max OS",
      "P770 2020",
      "P7MC",
      "P7MB",
      "SIM",
      "SIM Max",
      "SIM Max OS",
      "M5",
      "M6",
      "P760",
      "P790 2019",
      "P7TW",
      "M3",
      "M4",
      "M1",
      "M2 2017",
      "M CGB",
      "P730",
      "P750",
      "P770",
      "P790",
      "M2",
      "M2 Tour",
      "PSi",
      "PSi Tour",
      "RSi 1",
      "RSi 2",
      "RSi TP",
      "AeroBurner",
      "AeroBurner HL",
      "Speedblade",
      "Speedblade HL",
      "Tour Preferred CB",
      "Tour Preferred MB 2014",
      "Tour Preferred MC 2014",
      "Tour Preferred",
      "SpeedBlade",
      "SpeedBlade HL",
      "RocketBladez Max",
      "Tour Preferred MB",
      "Tour Preferred MC",
      "RocketBladez",
      "RocketBladez Tour",
      "RocketBallz",
      "RocketBallz Max",
      "R11",
      "Burner 2.0",
      "Burner 2.0 HP",
      "R9",
      "R9 TP",
      "R9 Max",
      "Burner",
      "r7 XD",
      "Burner Plus",
      "Tour Burner",
      "r7",
      "r7 Draw",
      "r7 TP",
      "RAC MB TP",
      "r7 CGB Max",
      "r5 XL",
      "RAC OS",
      "RAC TP"
    ],
    "Callaway": [
      "Elyte",
      "Elyte X",
      "Elyte HL",
      "Elyte Max Fast",
      "Apex Ai200",
      "Apex Ai300",
      "Apex Ti Fusion",
      "Apex MB",
      "Apex CB",
      "Apex Pro",
      "Paradym Ai Smoke",
      "Paradym Ai Smoke HL",
      "Paradym",
      "Paradym X",
      "Paradym Triple Diamond",
      "Rogue ST Max",
      "Rogue ST Max OS",
      "Rogue ST Pro",
      "X Forged CB 21",
      "Apex 21",
      "Apex Pro 21",
      "Apex DCB 21",
      "Apex TCB 21",
      "Big Bertha B21",
      "Mavrik",
      "Mavrik Max",
      "Mavrik Pro",
      "Apex 19",
      "Apex Pro 19",
      "X Forged 19",
      "Rogue",
      "Rogue Pro",
      "Rogue X",
      "X Forged 18",
      "Epic",
      "Epic Pro",
      "Apex CF16",
      "Apex 16",
      "Apex Pro 16",
      "Apex Black CF16",
      "Big Bertha OS",
      "Steelhead XR",
      "Steelhead XR Pro",
      "XR OS",
      "XR",
      "XR Pro",
      "X Series N415",
      "Apex",
      "Big Bertha",
      "X2 Hot",
      "X2 Hot Pro",
      "X Hot",
      "X Hot Pro",
      "X Forged 13",
      "Legacy Black",
      "RAZR X HL",
      "RAZR XF",
      "RAZR X Black",
      "RAZR X NG",
      "RAZR X",
      "RAZR X Forged",
      "RAZR X Tour",
      "RAZR X Muscleback",
      "Diablo Edge",
      "Diablo Edge Tour",
      "Diablo Forged",
      "X-24 Hot",
      "X-22",
      "X-22 Tour",
      "X-Forged 2009",
      "X-Forged",
      "FT i-brid",
      "X-20",
      "X-20 Tour",
      "X Forged 2007",
      "X-16",
      "X-16 Pro Series",
      "Fusion Wide Sole",
      "X-18",
      "X-18 Pro Series",
      "X Tour",
      "Fusion"
    ],
    "Titleist": [
      "T100",
      "T100S",
      "T150",
      "T200",
      "T350",
      "T300",
      "T400",
      "620 MB",
      "620 CB",
      "AP1 718",
      "AP2 718",
      "AP3 718",
      "U500",
      "U510",
      "T-MB 718",
      "AP1 716",
      "AP2 716",
      "AP3",
      "716 MB",
      "716 CB",
      "T-MB 716",
      "C16",
      "AP1 714",
      "AP2 714",
      "714 MB",
      "714 CB",
      "AP1 712",
      "AP2 712",
      "712 MB",
      "712 CB",
      "AP1 710",
      "AP2 710",
      "710 MB",
      "710 CB",
      "AP1",
      "AP2",
      "Z Blend Forged",
      "755 Forged",
      "775 Forged",
      "775 CB",
      "695 CB",
      "695 MB",
      "660 Forged",
      "681 Forged",
      "804 OS",
      "704 CB",
      "680 Forged",
      "690 CB",
      "690 MB",
      "670 Forged",
      "731 PM",
      "DCI 762",
      "DCI 762B",
      "DCI 822 OS",
      "DCI 990",
      "DCI 990B",
      "DCI 981",
      "DCI 981 SL",
      "DCI 962",
      "DCI 962B",
      "DCI Oversize+ Black",
      "DCI Oversize+ Gold",
      "DCI Black",
      "DCI Gold",
      "735 CM",
      "681 T Forged",
      "585.H",
      "585.CB",
      "DCI 981 SL Black",
      "Tour Model",
      "712 U",
      "U505"
    ],
    "Ping": [
      "i230",
      "G430",
      "G425",
      "Blueprint",
      "G410",
      "i210",
      "i500",
      "G400",
      "i400",
      "iBlade",
      "G",
      "G Max",
      "i Series",
      "G30",
      "i25",
      "S55",
      "Anser Forged",
      "G25",
      "i20",
      "S56",
      "G20",
      "i15",
      "S57",
      "G15",
      "Rapture V2",
      "i10",
      "G10",
      "S58",
      "Rapture",
      "G5",
      "i5",
      "G2",
      "S59",
      "i3 O-Size",
      "i3 Blade"
    ],
    "Cobra": [
      "Darkspeed",
      "King CB/MB",
      "King Tour",
      "Aerojet",
      "King Forged Tec Black",
      "King Forged Tec",
      "LTDx",
      "AIR-X",
      "Radspeed",
      "King Speedzone",
      "King F9 Speedback",
      "King Forged CB",
      "King Forged MB",
      "King F8",
      "King F7",
      "King F6",
      "Fly-Z",
      "Fly-Z XL",
      "Fly-Z Pro",
      "Bio Cell",
      "Baffler XL",
      "AMP Cell",
      "AMP",
      "S3",
      "S2",
      "S9",
      "Pro CB",
      "Pro MB",
      "FP",
      "King Cobra SS",
      "King Cobra SS-I"
    ],
    "Mizuno": [
      "Pro 245",
      "Pro 243",
      "Pro 241",
      "JPX 923 Hot Metal",
      "JPX 923 Hot Metal Pro",
      "JPX 923 Hot Metal HL",
      "JPX 923 Forged",
      "JPX 923 Tour",
      "Pro 225",
      "Pro 223",
      "Pro 221",
      "JPX 921 Hot Metal",
      "JPX 921 Forged",
      "JPX 921 Tour",
      "MP-20 HMB",
      "MP-20 MB",
      "MP-20 MMC",
      "MP-20 SEL",
      "JPX 919 Hot Metal",
      "JPX 919 Forged",
      "JPX 919 Tour",
      "MP-18 SC",
      "MP-18 MMC",
      "MP-18",
      "JPX 900 Hot Metal",
      "JPX 900 Forged",
      "JPX 900 Tour",
      "MP-25",
      "MP-5",
      "JPX EZ",
      "JPX-850",
      "JPX-850 Forged",
      "MP-15",
      "MP-H5",
      "MP-4",
      "MP-54",
      "JPX-825",
      "JPX-825 Pro",
      "MP-64",
      "MP-H4",
      "MP-53",
      "MP-63",
      "MP-69",
      "JPX-800",
      "MP-59",
      "MP-52",
      "MP-62",
      "MP-68",
      "MP-58",
      "MP-67",
      "MP-57",
      "MP-60",
      "MP-37",
      "MP-32",
      "MP-30",
      "MP-33",
      "MX-950",
      "MX-100",
      "MX-200",
      "MX-300",
      "MX-1000",
      "MX-900",
      "MX-25",
      "MX-19",
      "MX-17",
      "MX-23",
      "MX-20",
      "MX-15",
      "JPX-800 HD",
      "MP-29",
      "MP-14",
      "JPX-900 Forged",
      "JPX-825 HD",
      "MP-66",
      "T-ZOiD MP",
      "JPX EZ Forged",
      "MP-18 SC Fli-Hi",
      "MP-20 Fli-Hi",
      "JPX 919 Hot Metal HL",
      "JPX 921 Hot Metal HL",
      "MP-20 MMC Fli-Hi",
      "MX-500"
    ],
    "PXG": [
      "0311 P GEN7",
      "0311 XP GEN7",
      "0211 (2024)",
      "Black Ops",
      "0317 T",
      "0317 CB",
      "0317 ST",
      "0317 X Driving Iron",
      "0311 P GEN6",
      "0311 XP GEN6",
      "0311 T GEN5",
      "0311 P GEN5",
      "0311 XP GEN5",
      "0211 (2022)",
      "0311 GEN4",
      "0211",
      "0311 XP GEN2",
      "0311 P GEN3",
      "0311 XP GEN3",
      "0311 XF GEN2",
      "0311 T",
      "0311 Gen1",
      "0311 Gen2"
    ],
    "Honma": [
      "TW767 Tour V",
      "TW767 Vx",
      "TW767 Px",
      "TW767 Hx",
      "TW757 P",
      "TW757 Vx",
      "TW757 B",
      "GS",
      "TR21 X",
      "TR20 P",
      "TR20 V",
      "BERES 09 (2-Star)",
      "BERES 09 (3-Star)",
      "BERES Nx",
      "BERES 08 (2-Star)",
      "BERES 08 (3-Star)",
      "BERES 07 (2-Star)",
      "BERES 07 (3-Star)",
      "BERES 06 (2-Star)",
      "BERES 06 (3-Star)",
      "TW747 P",
      "TW747 Vx",
      "TW737 P",
      "TW737 Vx",
      "TW737 V",
      "TW737 Vs",
      "TW737 Vn",
      "TW727 P",
      "TW727 V",
      "Be ZEAL 535",
      "S-07",
      "S-06"
    ],
    "Wilson": [
      "Dynapower",
      "Dynapower MAX",
      "Dynapower Forged",
      "Staff Model Blade",
      "Staff Model CB",
      "D9",
      "D7 Forged",
      "Launch Pad 2",
      "Launch Pad",
      "C-300 Forged",
      "D-300",
      "C-200",
      "D-200",
      "D-100",
      "Ultra SGI",
      "Tour Velocity",
      "Pro Staff SGI",
      "Deep Red",
      "Deep Red Max"
    ],
    "Wilson Staff": [
      "Dynapower Forged",
      "Dynapower",
      "Dynapower MAX",
      "Staff Model Blade",
      "Staff Model CB",
      "Staff Model Utility",
      "D9",
      "D7 Forged",
      "D7",
      "Launch Pad 2",
      "Launch Pad",
      "FG Tour V6",
      "FG Tour 100",
      "FG Tour V4",
      "FG Tour V2",
      "Ci11",
      "Ci9",
      "D-300",
      "D-200",
      "D-150",
      "D-100"
    ],
    "Tour Edge": [
      "Exotics C725",
      "Exotics E725",
      "Exotics X725",
      "Exotics C724",
      "Exotics E724",
      "Hot Launch E524",
      "Hot Launch E525",
      "Hot Launch E525 Iron-Wood",
      "Exotics E722",
      "Exotics C722",
      "Hot Launch C522",
      "Hot Launch E522",
      "Hot Launch C521",
      "Hot Launch E521",
      "Exotics EXS 220",
      "Exotics E8",
      "Bazooka 470"
    ],
    "Miura": [
      "MB-101",
      "KM-700",
      "KM-Baby Blade",
      "TB-901",
      "MB-001",
      "Baby Blades",
      "Tournament Blade",
      "TC-202",
      "TC-201",
      "TC-101",
      "MC-502",
      "MC-501",
      "MC-101",
      "CB-302",
      "CB-801",
      "CB-1008",
      "CB-501",
      "CB-57",
      "IC-602",
      "IC-601",
      "PI-401"
    ]
  },
  "Wedges": {
    "TaylorMade": [
      "Milled Grind 5",
      "Hi-Toe 4",
      "Milled Grind 4",
      "Hi-Toe Big Foot",
      "Hi-Toe 3",
      "Milled Grind 3",
      "Milled Grind 3 Tiger Woods",
      "Hi-Toe Raw",
      "Milled Grind 2",
      "Milled Grind 2 Tiger Woods",
      "Hi-Toe",
      "Milled Grind",
      "Tour Preferred EF",
      "Tour Preferred EF Spin",
      "EF Spin",
      "Tour Preferred",
      "Tour Preferred EF 2014",
      "Tour Preferred EF Spin Groove",
      "ATV",
      "Z-TP",
      "Tour Preferred TP",
      "Tour Preferred UDI",
      "RAC TP xFT",
      "RAC Chrome",
      "RAC Satin",
      "RAC",
      "RAC LDP",
      "ATV Grind",
      "Milled Grind Hi-Toe"
    ],
    "Callaway": [
      "Opus",
      "CBX Full Face 2",
      "Jaws Raw Full Toe",
      "CB",
      "Jaws Raw Full Face",
      "CBX 4",
      "Jaws Raw",
      "Jaws Full Toe",
      "CBX Full Face",
      "Jaws MD5 Raw",
      "MD5 Jaws",
      "CBX 2",
      "Sure Out 2",
      "Mack Daddy Forged",
      "Mack Daddy CB",
      "PM Grind",
      "Sure Out",
      "CBX",
      "Mack Daddy 4",
      "Mack Daddy PM Grind",
      "MD3 Milled",
      "MD3",
      "Mack Daddy 3",
      "Mack Daddy 2",
      "Mack Daddy",
      "Mack Daddy 1",
      "X Forged",
      "X-Tour",
      "X Forged Vintage",
      "X-Series Jaws",
      "X Series",
      "X Series Tour",
      "Big Bertha"
    ],
    "Titleist": [
      "Vokey SM11",
      "Vokey SM10",
      "Vokey SM9",
      "Vokey SM8",
      "Vokey SM7",
      "Vokey SM6",
      "Vokey SM5",
      "Vokey SM4",
      "Vokey SM4 TVD",
      "Vokey SM3",
      "Vokey SM2",
      "Vokey SM1",
      "Vokey Spin Milled",
      "Vokey Oil Can",
      "Vokey Forged",
      "Vokey BV",
      "Vokey Tour BV",
      "Vokey Spin Milled Raw",
      "Vokey Progressive",
      "Vokey SM5 TVD",
      "Vokey SM6 TVD",
      "Vokey SM7 TVD"
    ],
    "Ping": [
      "S159",
      "S159 Custom",
      "Glide 4.0",
      "Glide 4.0 Stealth",
      "ChipR",
      "Glide 3.0",
      "Glide 2.0 Stealth",
      "Glide 2.0",
      "Glide",
      "S55",
      "Gorge Tour",
      "Gorge Tour-S",
      "Tour-S",
      "Tour-W",
      "S59"
    ],
    "Cobra": [
      "Snakebite",
      "King Forged Tec",
      "King MIM",
      "King PUR",
      "King V",
      "AMP Cell",
      "S3",
      "S9",
      "S2",
      "King Tour Wedge"
    ],
    "Mizuno": [
      "T24",
      "T22",
      "ES21",
      "T20",
      "T7",
      "S18",
      "S5",
      "MP-T5",
      "MP-R12",
      "MP-T11",
      "MP-T10",
      "MP-T",
      "MP-T4",
      "MP-R"
    ],
    "PXG": [
      "Sugar Daddy III",
      "0311 3X Forged",
      "Sugar Daddy II",
      "Sugar Daddy"
    ],
    "Honma": [
      "TW-W4",
      "TW-W"
    ],
    "Wilson": [
      "Staff Model Hi-Toe",
      "Staff Model"
    ],
    "Wilson Staff": [
      "Staff Model ZM",
      "Staff Model",
      "Staff Model Hi-Toe",
      "Dynapower MAX",
      "Harmonized",
      "D9",
      "FG Tour TC"
    ],
    "Tour Edge": [
      "TGS Wedge",
      "ES5 Wedge"
    ],
    "Miura": [
      "K-Grind 2.0",
      "Forged Wedge Series Y-Grind",
      "Forged Wedge Series C-Grind",
      "Milled Tour Wedge",
      "Passing Point 9003",
      "Y-Grind (Original)",
      "C-Grind (Original)",
      "Tour Wedge"
    ]
  },
  "Putters": {
    "TaylorMade": [
      "TP Black",
      "Spider GTx",
      "TP Reserve",
      "Spider GT",
      "Spider GT Silver",
      "Spider EX",
      "Spider X HydroBlast",
      "Truss",
      "Spider S",
      "Spider SR",
      "Spider FCG",
      "Spider X",
      "Spider Tour Black",
      "Spider Tour Platinum",
      "Spider Tour",
      "TP Collection",
      "Spider",
      "TP Collection 2016",
      "Spider Limited",
      "Daddy Long Legs",
      "Daddy Long Legs 2",
      "Ghost Tour Black",
      "Ghost Tour",
      "Ghost Tour Daytona",
      "Ghost Tour Monte Carlo",
      "Ghost Tour Maranello",
      "Ghost Manta",
      "Ghost Spider",
      "Ghost Spider S",
      "Tour Ghost",
      "Ghost",
      "Corza Ghost",
      "Rossa Daytona Ghost",
      "Rossa Fontana",
      "Rossa Sebring",
      "Daytona",
      "Rossa Monza",
      "Rossa Maranello",
      "Rossa Monte Carlo",
      "Rossa CGB",
      "Rossa",
      "Rossa CGB Sebring",
      "Rossa Corza"
    ],
    "Callaway": [
      "Ai-One Milled",
      "Ai-One",
      "Tri-Hot 5K",
      "2-Ball Ten",
      "White Hot OG",
      "Eleven",
      "Triple Track",
      "Stroke Lab Black",
      "Stroke Lab",
      "Toulon Design",
      "EXO",
      "Toulon",
      "O-Works",
      "White Hot RX",
      "Toe Up",
      "Works",
      "Works Big T",
      "Works Versa",
      "Works Versa Tank",
      "White Hot Pro 2.0",
      "Versa Tour",
      "Metal-X Milled",
      "Versa White",
      "Tank Versa",
      "Versa 90",
      "Tank",
      "Metal-X",
      "White Hot Pro",
      "Versa",
      "Flip Face",
      "White Ice 2.0",
      "2-Ball Blade",
      "White Ice",
      "ProType Tour",
      "White Hot 2-Ball",
      "White Hot XG 2.0",
      "Sabertooth",
      "Odyssey #7",
      "White Hot Tour",
      "Black Series i",
      "White Hot XG",
      "Black Series",
      "White Hot",
      "White Steel",
      "Odyssey White Hot",
      "Dual Force"
    ],
    "Ping": [
      "PLD Milled Anser",
      "PLD Milled Piper",
      "PLD Milled Tyne",
      "PLD Milled Oslo",
      "PLD Milled Bird Eye",
      "Heppler Anser 2",
      "Heppler ZB 3",
      "Heppler Piper",
      "Heppler Piper C",
      "Heppler Piper Armlock",
      "Heppler Fetch",
      "Heppler Floki",
      "Heppler Ketsch",
      "Heppler Tomcat 14",
      "Heppler Tyne 3",
      "Sigma 2 Anser",
      "Sigma 2 Arna",
      "Sigma 2 Kushin C",
      "Sigma 2 Tyne",
      "Sigma 2 Tyne 4",
      "Sigma 2 Wolverine H",
      "Sigma 2 Fetch",
      "Sigma 2 ZB 2",
      "Sigma 2 Valor",
      "Sigma 2 Darby",
      "Vault 2.0",
      "Vault",
      "Sigma G",
      "Karsten",
      "Scottsdale TR Anser 2",
      "Scottsdale TR B60",
      "Scottsdale TR Greyhawk",
      "Scottsdale TR Piper C",
      "Scottsdale TR Shea",
      "Scottsdale TR ZB S",
      "iWi",
      "Anser",
      "Scottsdale Anser",
      "Scottsdale B60",
      "Scottsdale Wolverine",
      "Scottsdale Shea",
      "Scottsdale Greyhawk",
      "Scottsdale ZB",
      "Scottsdale Piper",
      "Craz-E",
      "Redwood Anser",
      "Redwood Norman",
      "Redwood Craz-E",
      "B60",
      "Zing",
      "Zing 2",
      "Anser 2",
      "Anser 4",
      "Anser 5",
      "G Le2"
    ],
    "Cobra": [
      "King 3D Printed",
      "King Vintage",
      "King Cobra",
      "Trusty Rusty",
      "Fly-Z"
    ],
    "Mizuno": [
      "M-Craft OMOI",
      "M-Craft"
    ],
    "PXG": [
      "Battle Ready II Torpedo",
      "Battle Ready II",
      "Battle Ready",
      "Gunboat",
      "Mustang",
      "Brandon",
      "Gunboat Gen2",
      "Bat Attack"
    ],
    "Honma": [
      "PP-202",
      "PP-303",
      "BERES PP-201"
    ],
    "Wilson": [
      "Staff Model TM22",
      "Staff Model KM22",
      "Infinite"
    ],
    "Wilson Staff": [
      "Staff Model 8802",
      "Staff Model BL22",
      "Staff Model MT22",
      "Staff Model TM22",
      "Staff Model CS22",
      "Infinite Windy City",
      "Infinite West Loop",
      "Infinite Michigan Ave",
      "Infinite Grant Park",
      "Infinite Bucktown",
      "Infinite Buckingham",
      "Infinite Southside",
      "Infinite Bean",
      "Infinite South Side II",
      "Infinite Lake Shore",
      "Staff Model 8802 Classic"
    ],
    "Tour Edge": [
      "Wingman",
      "Template Series"
    ],
    "Scotty Cameron": [
      "Super Select Newport 2",
      "Super Select Newport 2 Plus",
      "Super Select Newport 2.5",
      "Super Select Squareback 2",
      "Super Select Fastback 1.5",
      "Super Select Del Mar",
      "Super Select GoLo 6",
      "Phantom X 5",
      "Phantom X 5.5",
      "Phantom X 7",
      "Phantom X 7.5",
      "Phantom X 9",
      "Phantom X 11",
      "Phantom X 12",
      "Special Select Newport 2",
      "Special Select Squareback 2",
      "Studio Design"
    ],
    "Odyssey": [
      "Ai-ONE Cruiser #7",
      "Ai-ONE Cruiser Double Wide",
      "Ai-ONE Cruiser Jailbird",
      "Ai-ONE #1",
      "Ai-ONE #7",
      "Ai-ONE Mill #1",
      "White Hot OG #1",
      "White Hot OG #7",
      "White Hot OG Rossie",
      "White Hot OG 2-Ball",
      "Eleven Tour Lined",
      "Eleven S",
      "Ten",
      "Ten S",
      "Tri-Hot 5K",
      "2-Ball Ten"
    ],
    "LA Golf": [
      "TP.1",
      "TP.2"
    ]
  }
};

// ─────── Flat per-category: brand → models[] ───────
const SHAFTS:        Record<string, string[]> = {
  "Fujikura": [
    "Ventus Blue",
    "Ventus Black",
    "Ventus Red",
    "Ventus White 2025",
    "Ventus TR Blue",
    "Ventus TR Blue 2.0",
    "Ventus TR Black",
    "Ventus TR Red",
    "Speeder NX Blue",
    "Speeder NX Green",
    "Speeder NX Red",
    "Speeder Evolution II",
    "Speeder Evolution III",
    "Speeder TR",
    "Speeder Pro",
    "Speeder Evolution 661",
    "Speeder Evolution 757",
    "Speeder Motore 661",
    "Speeder Motore 757",
    "Blur",
    "Atmos Tour Spec Blue",
    "Atmos Tour Spec Red",
    "Atmos Tour Spec Black",
    "Air Speeder",
    "Vista Pro 45",
    "Vista Pro 55",
    "Vista Pro 65",
    "Pro 2.0 Blue",
    "Pro 2.0 Black",
    "Motore X F1",
    "Motore X F3",
    "Motore X F5",
    "Ventus HB",
    "Speeder HB"
  ],
  "Project X": [
    "HZRDUS Black Gen 5",
    "HZRDUS Black Gen 4",
    "HZRDUS Smoke Black",
    "HZRDUS Silver Gen 4",
    "HZRDUS Yellow",
    "HZRDUS Green",
    "HZRDUS Red CB Gen 4",
    "HZRDUS Smoke Blue",
    "HZRDUS Smoke Red",
    "HZRDUS Smoke Fairway",
    "HZRDUS RDX Blue",
    "HZRDUS RDX Black",
    "EvenFlow Riptide",
    "EvenFlow Black",
    "EvenFlow Blue",
    "Cypher",
    "Catalyst 60",
    "Catalyst 70",
    "Catalyst 80",
    "PXi",
    "Rifle",
    "LZ (Loading Zone)",
    "IO",
    "LS",
    "Elevate Tour",
    "Dynamic Gold 97",
    "Dynamic Gold 105",
    "Dynamic Gold 120",
    "Dynamic Gold S300",
    "Dynamic Gold X100",
    "Dynamic Gold HT",
    "Dynamic Gold Tour Issue S400",
    "Dynamic Gold Tour Issue X100",
    "Dynamic Gold Mid 115",
    "Project X Rifle",
    "Project X 5.5",
    "Project X 6.0",
    "Project X 6.5",
    "AMT Tour White",
    "AMT Black"
  ],
  "Mitsubishi Chemical": [
    "Diamana WB (White Board)",
    "Diamana BB (Blue Board)",
    "Diamana RB (Red Board)",
    "Diamana GT",
    "Diamana PD",
    "Diamana TB",
    "Diamana S+",
    "Diamana ZF",
    "Diamana \\",
    "Diamana BF",
    "Tensei AV Raw White",
    "Tensei AV Raw Blue",
    "Tensei AV Raw Orange",
    "Tensei AV Raw White TXS",
    "Tensei 1K Pro White",
    "Tensei 1K Pro Blue",
    "Tensei 1K Pro Orange",
    "Tensei Pro Blue 1K",
    "Tensei CK Pro Orange",
    "Tensei CK Pro White",
    "Tensei CK Pro Blue",
    "Kai\\",
    "Kuro Kage",
    "VANQUISH VV",
    "Fubuki MV",
    "Bassara",
    "MMT 55",
    "MMT 65",
    "MMT 80",
    "MMT 105",
    "MMT 125"
  ],
  "KBS": [
    "Tour",
    "Tour 90",
    "Tour 2.0",
    "Tour V",
    "Tour Lite",
    "Tour FLT",
    "C-Taper",
    "C-Taper 120",
    "C-Taper Lite",
    "$-Taper",
    "$-Taper Lite",
    "Hi-Rev 2.0",
    "MAX",
    "TGI (Tour Graphite Iron)",
    "PGI (Players Graphite Iron)",
    "MAX Graphite",
    "TD",
    "TGI Hybrid",
    "CT Tour Putter",
    "GPS Putter"
  ],
  "Nippon": [
    "N.S.PRO Modus3 Tour 105",
    "N.S.PRO Modus3 Tour 110",
    "N.S.PRO Modus3 Tour 115",
    "N.S.PRO Modus3 Tour 120",
    "N.S.PRO Modus3 System3 Tour 125",
    "N.S.PRO Modus3 Tour 130",
    "N.S.PRO Modus3 Wedge",
    "N.S.PRO 750GH Neo",
    "N.S.PRO 850GH Neo",
    "N.S.PRO 950GH Neo",
    "N.S.PRO 750GH",
    "N.S.PRO 850GH",
    "N.S.PRO 950GH",
    "N.S.PRO 950GH HT",
    "N.S.PRO 1050GH",
    "N.S.PRO 1150GH",
    "N.S.PRO 1150GH Tour",
    "N.S.PRO V90",
    "N.S.PRO Zelos 6",
    "N.S.PRO Zelos 7",
    "N.S.PRO Zelos 8",
    "N.S.PRO Zelos 7 Hybrid",
    "N.S.PRO 850FW",
    "N.S.PRO 950FW"
  ],
  "Graphite Design": [
    "Tour AD UB",
    "Tour AD HD",
    "Tour AD XC",
    "Tour AD VR",
    "Tour AD IZ",
    "Tour AD TP",
    "Tour AD DI",
    "Tour AD GP",
    "Tour AD GC",
    "Tour AD CQ",
    "Tour AD FI",
    "Tour AD M9003",
    "Tour AD MJ",
    "Tour AD BB",
    "Tour AD SL II",
    "Tour AD PT",
    "Tour AD GT",
    "Tour AD F-Series",
    "Raune",
    "Raune Fairway",
    "Raune Hybrid",
    "MAD Pro",
    "MAD Standard",
    "Tour AD VF",
    "Tour AD IZ Hybrid",
    "Tour AD Iron 55-95",
    "aG33-3 Series"
  ],
  "Aldila": [
    "Rogue Black",
    "Rogue Silver",
    "Rogue Max",
    "Rogue Elite",
    "Rogue White",
    "NV Green",
    "NV Orange",
    "NV 2KXV Blue",
    "NV 2KXV Green",
    "NV 2KXV Orange",
    "RIP Alpha",
    "RIP Phenom",
    "Synergy",
    "Xtreme",
    "Ascent"
  ],
  "Aerotech": [
    "SteelFiber i70",
    "SteelFiber i80",
    "SteelFiber i95",
    "SteelFiber i110",
    "SteelFiber FC"
  ],
  "ACCRA": [
    "TZ5",
    "TZ6",
    "TZ7",
    "FX",
    "FX 2.0",
    "iSeries 85",
    "iSeries 95",
    "iSeries 105"
  ],
  "LA Golf": [
    "Trono",
    "Rebar",
    "DGLO",
    "P-Series",
    "Bryson"
  ],
  "Oban": [
    "Kiyoshi",
    "Devotion",
    "CT-125"
  ],
  "Paderson": [
    "Kinetixx"
  ],
  "Grafalloy": [
    "ProLaunch Blue",
    "ProLaunch Red",
    "ProLaunch Axis Blue",
    "BiMatrix"
  ],
  "Matrix": [
    "Ozik ALTUS 5.1",
    "Ozik ALTUS Fairway",
    "Ozik ALTUS Tour H8",
    "Ozik XCON 5",
    "Ozik XCON 6"
  ],
  "AutoFlex": [
    "SF505",
    "SF505X",
    "Dream 7"
  ],
  "TPT Golf": [
    "TPT 15",
    "TPT 19",
    "TPT 22"
  ]
};
const GRIPS:         Record<string, string[]> = {
  "Golf Pride": [
    "Tour Velvet",
    "Tour Velvet 360",
    "Tour Velvet ALIGN",
    "Tour Velvet Plus4",
    "MCC (Multi-Compound)",
    "MCC Plus4",
    "MCC ALIGN",
    "Z-Grip",
    "Z-Grip ALIGN",
    "CP2 Wrap",
    "CP2 Pro",
    "Tour Wrap 2G",
    "VDR"
  ],
  "SuperStroke": [
    "S-Tech",
    "S-Tech Cord",
    "S-Tech Plus",
    "Traxion Tour",
    "Traxion Wrap",
    "Traxion Claw",
    "Cross Comfort",
    "Pistol GT Tour",
    "Traxion Flatso",
    "Zenergy Tour",
    "S-Tech Pistol"
  ],
  "Lamkin": [
    "Crossline",
    "Crossline 360",
    "Z5",
    "Sonar",
    "Sonar Tour",
    "Sonar+ Plus",
    "ST Hybrid",
    "UTx",
    "R.E.L. 3GEN",
    "Sink Fit"
  ],
  "Iomic": [
    "Sticky 2.3",
    "Sticky Opus 2.3",
    "Black Armor 2.0",
    "iXX 2.3"
  ],
  "Winn": [
    "Dri-Tac",
    "Dri-Tac Wrap",
    "Excel Soft",
    "DuraTech"
  ],
  "Karma": [
    "Velour",
    "Evolution"
  ],
  "P2": [
    "Classic",
    "Aware"
  ]
};
const BALLS:         Record<string, string[]> = {
  "Titleist": [
    "Pro V1",
    "Pro V1x",
    "Pro V1x Left Dash",
    "AVX",
    "Tour Speed",
    "Tour Soft",
    "Velocity",
    "TruFeel",
    "DT TruSoft",
    "Pro V1 2023",
    "Pro V1x 2023",
    "Pro V1 2021",
    "Pro V1x 2021",
    "Pro V1 2019",
    "Pro V1x 2019",
    "Pro V1 2017",
    "Pro V1x 2017",
    "Pro V1 2015",
    "Pro V1x 2015",
    "Pro V1 2013",
    "Pro V1x 2013",
    "Pro V1 2011",
    "Pro V1x 2011",
    "Pro V1 2009",
    "Pro V1x 2009",
    "Pro V1 2007",
    "NXT Tour",
    "NXT Tour S",
    "Tour Soft 2022",
    "Tour Soft 2020",
    "Tour Soft 2018",
    "Velocity 2024",
    "Velocity 2022",
    "TruFeel 2024"
  ],
  "Callaway": [
    "Chrome Tour",
    "Chrome Tour X",
    "Chrome Soft",
    "Chrome Soft X",
    "Chrome Soft X LS",
    "Supersoft",
    "Supersoft MAX",
    "Supersoft 23",
    "ERC Soft",
    "Warbird",
    "Chrome Soft 2022",
    "Chrome Soft 2020",
    "Chrome Soft 2018",
    "Chrome Soft X 2022",
    "Hex Diablo",
    "HX Hot",
    "Diablo Tour",
    "HEX Aerodynamics",
    "Warbird Plus",
    "Supersoft Magna"
  ],
  "TaylorMade": [
    "TP5",
    "TP5x",
    "TP5 pix",
    "Tour Response",
    "Soft Response",
    "Distance+",
    "Noodle",
    "Kalea",
    "TP5 2024",
    "TP5x 2024",
    "TP5 2021",
    "TP5x 2021",
    "Tour Response Stripe",
    "SpeedSoft",
    "Project (a)",
    "Rocketballz",
    "Tour Preferred 2016",
    "Tour Preferred 2014",
    "Lethal",
    "Penta TP"
  ],
  "Bridgestone": [
    "Tour B X",
    "Tour B XS",
    "Tour B RX",
    "Tour B RXS",
    "Tour B XS 2022",
    "Tour B RXS 2022",
    "e6",
    "e6 Speed",
    "e12 Contact",
    "e12 Soft",
    "e12 Speed",
    "Lady Precept",
    "Treo",
    "e5",
    "Tour B330",
    "Tour B330S"
  ],
  "Srixon": [
    "Z-Star",
    "Z-Star XV",
    "Z-Star Diamond",
    "Z-Star 8",
    "Z-Star XV 8",
    "Z-Star Divide",
    "Z-Star 2021",
    "Z-Star XV 2021",
    "Z-Star 2019",
    "Q-Star Tour",
    "Q-Star Tour Divide",
    "Q-Star",
    "AD333",
    "UltiSoft",
    "Soft Feel",
    "Distance",
    "Q-Star Tour 2023",
    "Q-Star Tour 2021",
    "Marathon",
    "Soft Feel Lady",
    "AD333 Tour"
  ],
  "Mizuno": [
    "RB Tour",
    "RB Tour X",
    "RB 566",
    "RB Max"
  ],
  "Vice Golf": [
    "Pro Plus",
    "Pro",
    "Pro Soft",
    "Pro Zero",
    "Tour",
    "Tour Plus",
    "Drive",
    "Drive Neon",
    "Pro Plus 2024"
  ],
  "Snell Golf": [
    "MTB Black",
    "MTB X",
    "MTB Prime",
    "MTB Prime X",
    "Get Sum"
  ],
  "OnCore": [
    "Elixr",
    "Vero X1",
    "AVANT 55",
    "ELIXR"
  ],
  "Maxfli": [
    "Tour X",
    "Tour",
    "Straightfli"
  ],
  "Kirkland Signature": [
    "Signature v2.0",
    "Signature Performance+",
    "Signature v3.0"
  ],
  "Wilson": [
    "Staff Model",
    "Staff Model X",
    "Duo Soft",
    "Duo Soft+",
    "Duo Optix",
    "Triad"
  ],
  "Honma": [
    "TW-X",
    "TW-S",
    "D1"
  ],
  "Volvik": [
    "Vivid",
    "Vivid Soft",
    "Vivid Lite",
    "Vivid XT",
    "S4",
    "Tour S4",
    "Crystal",
    "XT AMT",
    "Condor"
  ],
  "Seed Golf": [
    "SD-01",
    "SD-02"
  ],
  "Cut Golf": [
    "Cut Blue",
    "Cut Grey",
    "Cut DC"
  ],
  "Sugar Golf": [
    "Sugar"
  ],
  "Pinnacle": [
    "Rush",
    "Soft",
    "Practice",
    "Gold"
  ],
  "Noodle": [
    "Noodle Long & Soft",
    "Noodle Easy Distance"
  ]
};
const CLOTHING:      Record<string, string[]> = {
  "FootJoy": [
    "ProDry Performance Polo",
    "ProDry Lisle Polo",
    "ProDry Sport Polo",
    "Stretch Pique Polo",
    "Lightweight Softshell Jacket",
    "ThermoSeries Hybrid Jacket",
    "ThermoSeries Pullover Hoodie",
    "ThermoSeries Vest",
    "HydroLite X Rain Jacket",
    "HydroLite X Rain Trousers",
    "HydroLite X Hoodie",
    "Performance Polo",
    "ProDry Short Sleeve Polo",
    "ThermoSeries Midlayer",
    "ProDry Stretch Chill-Out Pullover",
    "Golf Shorts",
    "Golf Trousers",
    "HydroLite X Jacket",
    "HydroKnit Jacket",
    "HydroKnit Trousers",
    "DryJoys Tour XP Jacket",
    "DryJoys Tour XP Trousers",
    "Performance Half-Zip Pullover",
    "ThermoSeries Base Layer Top",
    "ThermoSeries Trousers",
    "ThermoSeries Lightweight Insulated Jacket",
    "ThermoSeries Lightweight Insulated Vest",
    "Stretch Chill-Out Pullover",
    "DryJoys Select Rain Jacket",
    "DryJoys Select Rain Trousers",
    "Performance Vest",
    "Pique Polo"
  ],
  "Nike": [
    "Dri-FIT Victory Polo",
    "Dri-FIT Victory Long-Sleeve Polo",
    "Dri-FIT Tour Polo",
    "Dri-FIT Tour Knit Polo",
    "Tiger Woods Collection Polo",
    "Tiger Woods Collection Jacket",
    "Storm-FIT Victory Jacket",
    "Storm-FIT ADV Jacket",
    "Therma-FIT Victory Half-Zip",
    "Therma-FIT Victory Vest",
    "Shield Full-Zip Jacket",
    "Dri-FIT UV Victory Polo",
    "Dri-FIT Tour Shorts",
    "Dri-FIT Tour Trousers",
    "Dri-FIT Victory Shorts",
    "Dri-FIT Player Polo",
    "Storm-FIT Victory Trousers",
    "Therma-FIT ADV Repel Jacket",
    "Shield Victory Half-Zip",
    "Dri-FIT Tour Knit Golf Trousers",
    "Tour Premium Polo",
    "Flex Golf Shorts",
    "Flex Golf Trousers",
    "Storm-FIT ADV Classic Jacket",
    "Dri-FIT Victory Base Layer",
    "Dri-FIT ADV Tour Polo",
    "Dri-FIT Victory Stripe Polo",
    "Therma-FIT ADV Vest",
    "Repel Player Jacket",
    "Dri-FIT Player Shorts"
  ],
  "Adidas": [
    "Ultimate365 Polo",
    "Ultimate365 Printed Polo",
    "Ultimate365 Tweedmill Polo",
    "Ultimate365 Tour Polo",
    "Ultimate365 Cold.RDY Base Layer",
    "Ultimate365 Cold.RDY Hoodie",
    "Ultimate365 Cold.RDY Jacket",
    "RAIN.RDY Jacket",
    "RAIN.RDY Trousers",
    "Go-To Polo",
    "Go-To Pique Polo",
    "Adicross Pullover",
    "Primegreen Polo",
    "Ultimate365 Tour Shorts",
    "Ultimate365 Tapered Trousers",
    "Cold.RDY Jacket",
    "Cold.RDY Vest",
    "Rain.RDY Pro Jacket",
    "Primegreen Performance Polo",
    "Primeblue Polo",
    "Go-To Shorts",
    "Go-To Trousers",
    "Cold.RDY Half-Zip Pullover",
    "Rain.RDY Jacket",
    "Cold.RDY Trousers",
    "Adicross Shorts",
    "Ultimate365 Long Sleeve Polo",
    "Primeblue Striped Polo",
    "Statement Full-Zip Jacket",
    "Rain.RDY Softshell Jacket",
    "Ultimate365 3-Stripes Polo"
  ],
  "Under Armour": [
    "Iso-Chill Polo",
    "Iso-Chill Printed Polo",
    "Playoff 3.0 Polo",
    "T2G Polo",
    "Storm Polo",
    "Performance Polo",
    "ColdGear Infrared Base Layer",
    "ColdGear Infrared Golf Trousers",
    "Drive Pro Insulated Jacket",
    "Drive Pro Storm Insulated Jacket",
    "Drive Pro Insulated Vest",
    "Drive Midlayer",
    "Matchplay Trousers",
    "Drive Pants",
    "Drive Golf Shorts",
    "Storm SweaterFleece Quarter-Zip",
    "Storm Windstrike Jacket",
    "Storm Windstrike Vest",
    "ColdGear Infrared Pullover",
    "Storm SweaterFleece Vest",
    "Storm Rain Jacket",
    "Storm Rain Trousers",
    "Launch Polo",
    "Playoff 3.0 Long-Sleeve Polo",
    "ColdGear Base Layer Leggings"
  ],
  "Puma": [
    "Cloudspun Polo",
    "Cloudspun Highway Polo",
    "Cloudspun Primary Polo",
    "MATTR Polo",
    "MATTR Brigade Polo",
    "MATTR Cloudspun Polo",
    "Volition America Polo",
    "Dealer Trousers",
    "Tailored Jackpot Trousers",
    "Jackpot Golf Shorts",
    "Cloudspun Full-Zip Jacket",
    "Storm Waterproof Jacket",
    "EGW Polo",
    "EGW Shorts",
    "EGW Trousers",
    "Cloudspun WRMLTH Polo",
    "MATTR Palms Polo",
    "Cloudspun Full-Zip Vest",
    "Pounce Shorts",
    "Storm Waterproof Trousers",
    "MATTR Move Polo"
  ],
  "Galvin Green": [
    "LANCE Interface-1 Jacket",
    "ARLIE GORE-TEX Jacket",
    "DWIGHT Insula Sweater",
    "DENNY Insula Jacket",
    "APOLLO GORE-TEX Jacket",
    "ALBIN Interface-1 Jacket",
    "ALF Polo",
    "AXEL Interface-1 Vest",
    "ALAN Insula Vest",
    "LUNA Interface-1 Jacket",
    "BELLA Insula Jacket",
    "NEVE Polo",
    "MORGAN Trousers",
    "LINCOLN Interface-1 Jacket",
    "NOAH GORE-TEX Jacket",
    "ROSS Polo",
    "ELTON SilverDry Polo",
    "PARKER Insula Vest",
    "DAMIAN Interface-1 Shorts",
    "GABRIEL Trousers",
    "LORETTA GORE-TEX Jacket",
    "VIOLA Interface-1 Jacket",
    "MARTY Interface-1 Jacket",
    "HARVEY Insula Jacket",
    "DALE Trousers",
    "MELODY GORE-TEX Jacket",
    "FRIDA Insula Jacket"
  ],
  "BOSS": [
    "Paddy Pro Polo",
    "Paddy Curved Polo",
    "Paul Polo",
    "Paule Polo",
    "J-Trim Polo",
    "Saul Quarter-Zip Jumper",
    "Zofin Athletic Sweater",
    "Hyne Full-Zip Jacket",
    "Paddy Trousers",
    "Sato Golf Shorts",
    "Loris Polo",
    "Waterproof Jacket",
    "Golf Shorts"
  ],
  "Ralph Lauren": [
    "RLX Performance Polo",
    "RLX Classic Fit Performance Polo",
    "RLX Striped Classic Fit Polo",
    "RLX Stretch Jersey Polo",
    "Polo Golf Classic Fit Polo",
    "RLX Bonded Softshell Jacket",
    "RLX Windbreaker Jacket",
    "RLX Quarter-Zip Pullover",
    "RLX Golf Vest",
    "RLX Tech Trousers",
    "RLX Stretch Shorts",
    "RLX Waterproof Jacket"
  ],
  "Lyle & Scott": [
    "Golf Tech Polo",
    "Players Polo",
    "Tonal Tech Polo",
    "Knitted Grid Polo",
    "Golf Windbreaker",
    "Moffat Quarter-Zip",
    "Quarter-Zip Sweater",
    "Crew Neck Sweater",
    "Golf Waterproof Jacket",
    "Golf Trousers",
    "Waterproof Jacket",
    "Golf Shorts"
  ],
  "Castore": [
    "Essential Performance Polo",
    "Club Golf Polo",
    "Pinnacle Engineered Knit Polo",
    "Printed Performance Polo",
    "Lightweight Waterproof Jacket",
    "Waterproof Over Trousers",
    "Soft Shell Tech Half-Zip",
    "Tech Fleece Full-Zip",
    "Insulated Vest",
    "Contoured Performance Shorts",
    "Performance Trousers",
    "Performance Polo",
    "Base Layer Top",
    "Insulated Jacket",
    "Golf Shorts"
  ],
  "J.Lindeberg": [
    "Tour Tech Slim Fit Polo",
    "Tour Tech Regular Fit Polo",
    "Tour Tech Long-Sleeve Polo",
    "Archer Polo",
    "Kv Polo",
    "Elof Regular Fit Polo",
    "Vent Polo",
    "Jay Jacket",
    "Liam Trouser",
    "Elias Short",
    "Lena Polo",
    "Bridge Full-Zip Mid Layer",
    "Waterproof Jacket",
    "Waterproof Trousers",
    "Lena Trousers"
  ],
  "Peter Millar": [
    "Crown Comfort Polo",
    "Crown Comfort Quarter-Zip",
    "Crown Sport Performance Polo",
    "Crown Sport Camo Polo",
    "Crown Crafted Performance Polo",
    "Hyperlight Performance Polo",
    "Performance Knit Half-Zip",
    "Tradewinds Stretch Trouser",
    "Crown Sport Short",
    "Crown Sport Polo",
    "Midlayer Vest",
    "Hyperlight Stretch Polo",
    "Banzai Full-Zip Jacket",
    "Weekend Shorts"
  ],
  "Kjus": [
    "Pro 3L 2.0 Jacket",
    "Pro 3L 3.0 Jacket",
    "Pro 3L Trousers",
    "Dexter 2.5L Jacket",
    "Release Half-Zip",
    "Dorian Casual Jacket",
    "Radiation Polo",
    "Luan Polo",
    "Iker Trousers",
    "Ice Polo",
    "Sense Half-Zip",
    "Radiation Long-Sleeve Polo",
    "Lars Insula Vest",
    "Percy Short",
    "Dorian Half-Zip",
    "Pro 3L Jacket",
    "Formula Polo"
  ],
  "Callaway": [
    "Opti-Dri Performance Polo",
    "Opti-Dri Chev Polo",
    "Opti-Stretch Solid Polo",
    "Swing Tech Opti-Dri Polo",
    "Weather Series Jacket",
    "Weather Series Trousers",
    "Tour Performance Polo",
    "Block Performance Polo",
    "Golf Midlayer Jacket",
    "Golf Shorts",
    "Chev Trousers",
    "Opti-Dri Sleeveless Polo",
    "Weather Series Half-Zip",
    "Golf Vest"
  ],
  "Ping": [
    "SensorCool Polo",
    "SensorCool Approach Polo",
    "Ramsey Polo",
    "Bradley Polo",
    "Lenny Polo",
    "Lincoln Polo",
    "Latham Midlayer",
    "Ashbourne Vest",
    "PING Waterproof Jacket",
    "Vault Shorts",
    "Golf Trousers",
    "Waterproof Trousers",
    "Long-Sleeve Polo",
    "Golf Shorts",
    "Tailored Fit Polo",
    "Jay Half-Zip",
    "Lenny Vest",
    "Holt Polo",
    "Tour Trousers",
    "Lightweight Hoodie",
    "Waterproof Jacket"
  ],
  "Glenmuir": [
    "Performance Polo",
    "Deacon Performance Polo",
    "Torrance Micro-Stripe Polo",
    "Kinloch Cotton Polo",
    "Kippen Polo",
    "Merino Quarter-Zip",
    "Merino Crew-Neck Sweater",
    "Merino V-Neck Sweater",
    "Kinloch Polo",
    "Piper Polo",
    "Wick Polo",
    "Merino Zip-Neck Vest",
    "Cotton Crew Neck Sweater",
    "Dunbar Polo",
    "Airfield Polo",
    "Kinloch Long-Sleeve Polo",
    "Merino Vest",
    "Long-Sleeve Polo",
    "Torrance Polo"
  ],
  "Oscar Jacobson": [
    "Chap Tour Polo",
    "Chap Course Polo",
    "Hartford Polo",
    "Milford Polo",
    "Marco Polo",
    "Golf Midlayer",
    "Waterproof Jacket",
    "Performance Trousers",
    "Chap Polo",
    "Birdie Polo",
    "Eagle Polo",
    "Midlayer Half-Zip",
    "Stretch Golf Trousers"
  ],
  "Original Penguin": [
    "Heritage Polo",
    "Heritage Stripe Polo",
    "Earl Polo",
    "Performance Earl Polo",
    "Pete Polo",
    "Heritage Oversized Pete Polo",
    "Performance Polo",
    "Novelty Print Polo",
    "Golf Trousers",
    "Bing Polo",
    "Golf Shorts"
  ],
  "TravisMathew": [
    "The Heater Polo",
    "The Heater Long-Sleeve Polo",
    "The Zinna 2.0 Polo",
    "El Capitan Polo",
    "Cloud Polo",
    "Open To Close Polo",
    "Half-Zip Pullover",
    "Full-Zip Jacket",
    "Golf Shorts",
    "Golf Trousers",
    "Belfair Polo",
    "Coto Crest Quarter-Zip",
    "Del Mar Trouser"
  ],
  "G/FORE": [
    "Tech Jersey Polo",
    "Optic Floral Tech Jersey Polo",
    "3/G\\",
    "Brushed Back Tech Quarter-Zip",
    "Luxe Mid Quarter-Zip",
    "Long Driver Polo",
    "Killer T Polo",
    "Performance Shorts",
    "Golf Trousers",
    "Full-Zip Jacket",
    "Tosca Shorts",
    "Warbird Tech Jersey Polo",
    "Circle G Polo"
  ],
  "Bunker Mentality": [
    "Krew Polo",
    "Delta Polo",
    "Tech Quarter-Zip",
    "Tri-Colour Quarter-Zip",
    "Augusta Zip Sweatshirt",
    "Tech Gilet",
    "Performance Polo",
    "Golf Trousers",
    "Golf Shorts",
    "Stripe Quarter-Zip",
    "Signature Polo",
    "Waterproof Jacket",
    "Classic Golf Short"
  ],
  "Abacus": [
    "Scramble Polo",
    "Lds Scramble Polo",
    "Glade Polo",
    "Trenton Polo",
    "Tina Long-Sleeve Polo",
    "Cray Waterproof Jacket",
    "Cray Waterproof Trousers",
    "Performance Polo",
    "Fleece Midlayer",
    "Lds Golf Shorts",
    "Granna Polo",
    "Biksmon Polo",
    "Waterproof Jacket",
    "Lds Glade Polo",
    "Lds Trenton Long Sleeve Polo",
    "Lds Links Jacket",
    "Lds Waterproof Trousers",
    "Monterey Polo",
    "Devons Polo"
  ],
  "Sunderland": [
    "Whisperdry Pro-Lite Jacket",
    "Whisperdry Pro-Lite Trousers",
    "Whisperdry Jacket",
    "Quebec Waterproof Jacket",
    "Quebec Waterproof Trousers",
    "Vermont Waterproof Jacket",
    "Vancouver Waterproof Trousers",
    "Vancouver Waterproof Jacket",
    "Performance Polo",
    "Midlayer Jacket",
    "Golf Shorts",
    "Alberta Waterproof Jacket",
    "Ontario Waterproof Trousers",
    "Pro-Flex Waterproof Jacket",
    "Whisperdry Tour Jacket",
    "Tech Fleece",
    "Pro-Flex Gilet"
  ],
  "Stuburt": [
    "Evolve-Sport Polo",
    "Evolve-Sport Waterproof Jacket",
    "Evolve-Sport Waterproof Trousers",
    "Evolve-Sport Full-Zip Fleece",
    "Evolve-Sport Half-Zip Fleece",
    "Evolve-Sport Padded Gilet",
    "Evolve-Sport Padded Jacket",
    "Arctic Lined Sweater",
    "Endurance-Sport Waterproof Jacket",
    "Endurance-Lite Waterproof Jacket",
    "Performance Polo",
    "Evolve-Sport Shorts",
    "Evolve-Sport Trousers",
    "Evolve-Sport Long-Sleeve Polo",
    "Sport Polo",
    "Evolve-Sport Windshirt",
    "Arctic Half-Zip"
  ],
  "ProQuip": [
    "Pro-Flex Waterproof Jacket",
    "Pro-Flex Waterproof Trousers",
    "TourFlex Elite Waterproof Jacket",
    "TourFlex Elite Waterproof Trousers",
    "TourFlex 360 Waterproof Jacket",
    "TourFlex 360 Waterproof Trousers",
    "TourFlex-Lite Waterproof Jacket",
    "Tempest Waterproof Jacket",
    "Tempest Waterproof Trousers",
    "Liberty Waterproof Jacket",
    "Liberty Waterproof Trousers",
    "Pro-Flex Gilet",
    "TourFlex Elite Gilet"
  ],
  "Island Green": [
    "Performance Polo",
    "Mesh Contrast Polo",
    "Full-Zip Jacket",
    "Mid-Layer Fleece",
    "Waterproof Jacket",
    "Waterproof Trousers",
    "Gilet Vest",
    "Golf Shorts",
    "Golf Trousers",
    "Long-Sleeve Polo",
    "Thermal Base Layer",
    "Full-Zip Fleece",
    "Ladies Performance Polo"
  ],
  "Calvin Klein Golf": [
    "Parramore Polo",
    "Delaware Polo",
    "Avenue Polo",
    "Harlem Polo",
    "Golf Tech Polo",
    "Midlayer Jacket",
    "Waterproof Jacket",
    "Golf Trousers",
    "Golf Shorts",
    "Knitted Midlayer",
    "Bryn Polo",
    "Jasper Quarter-Zip",
    "Gilet Vest"
  ],
  "Stromberg": [
    "Weather Tech Polo",
    "Weather Tech Waterproof Jacket",
    "Weather Tech Stretch Trousers",
    "Heritage Polo",
    "Heritage Classic Trouser",
    "Players Polo",
    "Players Trouser",
    "Golf Shorts",
    "Midlayer Fleece",
    "Waterproof Trousers",
    "Heritage Shorts",
    "Players Shorts",
    "Performance Polo",
    "Thermal Midlayer",
    "Gilet"
  ]
};
const HATS:          Record<string, string[]> = {
  "Titleist": [
    "Tour Performance",
    "Tour Performance Mesh",
    "Players Performance",
    "Players Performance Ball Marker Women",
    "Players StaDry",
    "Players StaDry Bucket",
    "Montauk Lightweight",
    "Tour Performance Visor",
    "Players Classic Visor",
    "Players Beanie",
    "Boardwalk Rope",
    "Tour Classic",
    "Tour Performance StaDry",
    "Players Performance StaDry",
    "Women",
    "Players Performance Mesh",
    "Players Visor",
    "Players Classic"
  ],
  "TaylorMade": [
    "Tour Radar",
    "Tour Litetech",
    "Tour Cage",
    "Tour Flat Bill",
    "Performance Cage",
    "Performance",
    "Tour Women",
    "Lifestyle Radar",
    "Women"
  ],
  "Callaway": [
    "Tour Authentic Performance Pro",
    "Performance Pro",
    "Riviera",
    "CG",
    "Women",
    "Tour Authentic Visor",
    "Relaxed Custom",
    "Stitch Magnet",
    "Rogue Bucket"
  ],
  "Ping": [
    "Tour Vented Delta",
    "Tour Classic",
    "Tour Delta",
    "P Cap",
    "Unstructured",
    "Eye Cap Visor",
    "Women"
  ],
  "Cobra": [
    "Tour Crown Snapback 2.0",
    "Crown C Snapback",
    "King Cobra Snapback",
    "King Cobra Rope Snapback",
    "King High Crown Visor",
    "Tour Tech"
  ],
  "Under Armour": [
    "Iso-Chill Driver Mesh",
    "Iso-Chill Driver",
    "Blitzing",
    "Jordan Spieth Tour",
    "Jordan Spieth Iso-Chill Tour 2.0",
    "Jordan Spieth Drive",
    "Women"
  ],
  "Nike": [
    "Dri-FIT ADV AeroBill Heritage86",
    "Dri-FIT ADV AeroBill Heritage86 Women",
    "AeroBill Heritage86",
    "Legacy91",
    "Dri-FIT Tiger Woods Legacy91",
    "Dri-FIT Featherlight",
    "AeroBill Visor"
  ],
  "Adidas": [
    "3-Stripes Tour",
    "Tour 3-Stripe",
    "Tour 3-Stripes Printed",
    "Golf 3-Stripes",
    "Performance Visor",
    "Women"
  ],
  "FootJoy": [
    "FJ Performance",
    "DryJoys Tour Bucket",
    "DryJoys Premium Bucket",
    "FJ ProDry",
    "FJ Visor",
    "HydroKnit Beanie"
  ],
  "Puma": [
    "Tour Driver",
    "P Cap Snapback",
    "Women"
  ],
  "J.Lindeberg": [
    "Caden",
    "Caden FW",
    "Harry",
    "Angus",
    "Women"
  ],
  "Galvin Green": [
    "Art Waterproof",
    "Asher Waterproof Bucket",
    "Atlas Waterproof",
    "Argo Waterproof",
    "Aqua Cresting Waterproof"
  ],
  "TravisMathew": [
    "The Chaperone",
    "Dunes",
    "Corral",
    "Monterey"
  ],
  "G/FORE": [
    "Pray For Birdies Patch Perforated Delta",
    "Pray For Birdies Snapback",
    "Pray For Birdies Bucket",
    "Circle G",
    "Gradient Circle G"
  ],
  "Ahead": [
    "The Original",
    "Extreme Fit",
    "Stratus Performance",
    "Frio Performance",
    "Tour Visor"
  ],
  "Imperial": [
    "The Original Buckle",
    "Tour Visor",
    "Structured Performance Adjustable",
    "Rope Cap",
    "Performance Stretch"
  ],
  "BOSS": [
    "Performance Cap",
    "Structured Cap",
    "Logo Cap",
    "Women",
    "Golf Beanie",
    "Golf Visor"
  ],
  "Srixon": [
    "Tour Cap",
    "Basic Cap",
    "Heathered Cap",
    "Cleveland Tour Cap",
    "Cleveland Bloom Cap"
  ],
  "Oscar Jacobson": [
    "Tour Cap",
    "Golf Cap",
    "Rain Cap",
    "Women",
    "Golf Beanie"
  ],
  "Original Penguin": [
    "Heritage Pete Cap",
    "Performance Cap",
    "Vintage Logo Cap",
    "Women",
    "Golf Visor"
  ]
};
const SUNGLASSES:    Record<string, string[]> = {
  "Oakley": [
    "Flak 2.0 XL",
    "Radar EV Path",
    "Radar EV Path Prizm Golf Polarized",
    "RadarLock Path",
    "Sutro",
    "Sutro S",
    "Jawbreaker",
    "EVZero Path",
    "Half Jacket 2.0 XL",
    "Holbrook",
    "Frogskins"
  ],
  "Maui Jim": [
    "Ho",
    "Banyans",
    "Breakwall",
    "Hot Sands",
    "Lighthouse",
    "Kanaha",
    "Peahi",
    "Makaha"
  ],
  "SunGod": [
    "Sierras",
    "Renegades",
    "Vulcans",
    "Zephyrs",
    "Tempests",
    "Paces",
    "Classics"
  ],
  "Tifosi": [
    "Seek FC 2.0",
    "Swank",
    "Swank XL",
    "Rail",
    "Rail XC",
    "Kilo",
    "Podium XC"
  ],
  "Bollé": [
    "Volt+",
    "Bolt 2.0",
    "Flash",
    "Lightshifter",
    "Lightshifter XL",
    "Chronoshield"
  ],
  "Under Armour": [
    "Blitzing",
    "Force",
    "Tuned Golf",
    "Igniter 2",
    "Gametime"
  ],
  "Nike Vision": [
    "Show X3",
    "Show X3 Elite",
    "Windshield",
    "Adrenaline 2",
    "Valiant"
  ],
  "Ray-Ban": [
    "Wayfarer Classic",
    "Aviator Classic",
    "Clubmaster Classic",
    "New Wayfarer"
  ],
  "Costa Del Mar": [
    "Brine II",
    "Fantail Pro",
    "Tuna Alley",
    "Tuna Alley Pro",
    "Fisch",
    "Blackfin Pro"
  ]
};
const GLOVES:        Record<string, string[]> = {
  "FootJoy": [
    "StaSof",
    "WeatherSof",
    "Pure Touch Limited",
    "HyperFLX",
    "Contour FLX",
    "GTxtreme",
    "SciFlex",
    "SofJoy",
    "TropiCool",
    "RainGrip",
    "WinterSof",
    "StaSof Winter",
    "StaCooler",
    "StaCooler Sport",
    "Junior"
  ],
  "Titleist": [
    "Players Flex",
    "Perma-Soft"
  ],
  "Callaway": [
    "Tour Authentic",
    "Tour Authentic Ai Smoke",
    "Dawn Patrol",
    "X-Tech",
    "Apex Tour",
    "Weather Spann",
    "Thermal Grip",
    "Rain Spann",
    "Thermal Mittens"
  ],
  "TaylorMade": [
    "Tour Preferred",
    "Tour Preferred Flex",
    "Tour Preferred Motion",
    "Stratus Tech",
    "Rain Control"
  ],
  "Ping": [
    "Tour",
    "Sport",
    "Sensor Sport"
  ],
  "Mizuno": [
    "Tour",
    "Comp",
    "Pro"
  ],
  "Srixon": [
    "Cabretta Leather",
    "All Weather",
    "Ball Marker"
  ],
  "Under Armour": [
    "Iso-Chill",
    "Spieth Tour",
    "Strikeskin Tour"
  ],
  "Bionic": [
    "StableGrip",
    "PerformanceGrip",
    "RelaxGrip 2.0",
    "AquaGrip"
  ],
  "Zero Friction": [
    "Cabretta",
    "Performance",
    "Storm"
  ],
  "G/FORE": [
    "Collection",
    "Delta Force"
  ],
  "Hirzl": [
    "Trust Control 2.0",
    "Trust Hybrid Plus",
    "Trust Feel"
  ]
};
const SHOES:         Record<string, string[]> = {
  "FootJoy": [
    "Pro|SLX",
    "Pro|SL",
    "HyperFlex",
    "HyperFlex Carbon",
    "HyperBoot",
    "Tour Alpha",
    "Premiere Series Packard",
    "Premiere Series Field",
    "Premiere Series Field LX",
    "Quantum",
    "Stratos",
    "FJ Flex",
    "FJ Fuel",
    "Traditions",
    "Contour",
    "StormWalker"
  ],
  "Ecco": [
    "BIOM H5",
    "BIOM H5 High Top BOA",
    "BIOM H4",
    "BIOM C4",
    "BIOM G5",
    "BIOM Tour",
    "Street 720",
    "S-Three"
  ],
  "Nike": [
    "Air Zoom Infinity Tour NEXT% 2",
    "Air Zoom Infinity Tour 3",
    "Infinity Tour 2 GORE-TEX",
    "Air Max 90 G",
    "Air Jordan 1 Low G",
    "TW 71",
    "Victory Pro 3"
  ],
  "Adidas": [
    "Tour360 24 Boost",
    "Tour360 24",
    "Codechaos 24",
    "Adizero ZG",
    "S2G Rain.RDY",
    "Solarmotion BOA",
    "ZG23",
    "CodeChaos Earth"
  ],
  "Puma": [
    "Alphacat NITRO Elite",
    "Ignite Articulate",
    "Ignite PWRADAPT",
    "Ignite NXT",
    "Royales",
    "Deviate Nitro"
  ],
  "G/FORE": [
    "Gallivan2r",
    "MG4+",
    "Gallivanter"
  ],
  "New Balance": [
    "574 Greens V2",
    "Fresh Foam Contend",
    "Fresh Foam X Defender"
  ],
  "Under Armour": [
    "Charged Draw 2",
    "HOVR Drive 2",
    "Spieth 5"
  ],
  "Skechers": [
    "GO GOLF Elite 5",
    "GO GOLF Max 3"
  ],
  "Payntr": [
    "X 005"
  ],
  "Duca del Cosma": [
    "Churchill"
  ]
};
const BAGS:          Record<string, string[]> = {
  "Ping": [
    "Hoofer",
    "Hoofer 14",
    "Hoofer Lite",
    "Moonlander",
    "DLX",
    "Pioneer",
    "Traverse",
    "L8"
  ],
  "Titleist": [
    "Players 4 Carbon",
    "Players 4 StaDry",
    "Players 5 StaDry",
    "Hybrid 14 StaDry",
    "Cart 14",
    "Premium",
    "LinksLegend Classic",
    "Tour Series"
  ],
  "Sun Mountain": [
    "2.5+",
    "4.5 LS",
    "Ridgeline 3",
    "C130",
    "C130 Hybrid",
    "Sync",
    "H2NO Lite",
    "Eco-Lite"
  ],
  "Callaway": [
    "Fairway C HD",
    "Fairway 14 HD",
    "Hyperlite Zero",
    "Chev Stand",
    "ORG 14",
    "Chev 14",
    "Tour Staff"
  ],
  "TaylorMade": [
    "FlexTech Lite",
    "FlexTech Crossover",
    "Pro Stand 24",
    "Pro Cart 24",
    "Cart Lite",
    "Pro Staff"
  ],
  "Cobra": [
    "Ultralight Pro Stand",
    "Ultralight Stand",
    "Ultralight Cart"
  ],
  "Big Max": [
    "Dri Lite Hybrid Plus",
    "Aqua Style 4",
    "Aqua Sport 4"
  ],
  "Bag Boy": [
    "Chiller",
    "Revolver FX"
  ],
  "Motocaddy": [
    "Pro Series",
    "Dry Series"
  ],
  "Ogio": [
    "Fuse Stand",
    "Woode 8 Hybrid"
  ],
  "Vessel": [
    "Player IV Pro",
    "VLX Stand",
    "Staff Bag"
  ],
  "Wilson": [
    "Exo Lite",
    "Staff Quiver"
  ]
};
const HEADCOVERS:    Record<string, string[]> = {
  "TaylorMade": [
    "Qi35 Driver Headcover",
    "Qi35 Fairway Headcover",
    "Qi35 Rescue Headcover",
    "Spider Putter Cover",
    "TP Blade Putter Cover",
    "Tour Staff Headcover"
  ],
  "Callaway": [
    "Ai Smoke Driver Headcover",
    "Paradym Driver Headcover",
    "Vintage Collection",
    "Fairway C Headcover"
  ],
  "Titleist": [
    "Jet Black Leather",
    "Tour Staff",
    "Barrel Headcover"
  ],
  "Ping": [
    "G440 Driver Headcover",
    "Icon Blade Putter",
    "Core Driver Headcover"
  ],
  "Cobra": [
    "Darkspeed Driver",
    "Puma Crown Headcover"
  ],
  "Mizuno": [
    "Pro Driver Headcover",
    "JPX Driver Headcover"
  ],
  "Cleveland": [
    "Launcher XL Driver"
  ],
  "Srixon": [
    "ZX5 Mk II Headcover"
  ],
  "Daphne's": [
    "Animal Headcovers",
    "Tiger",
    "Corgi"
  ],
  "Scotty Cameron": [
    "Gallery Putter Cover"
  ],
  "Odyssey": [
    "Ten Mallet Cover"
  ]
};
const RANGEFINDERS:  Record<string, string[]> = {
  "Bushnell": [
    "Pro X3+LINK",
    "Pro X3+",
    "Pro X3",
    "Tour Hybrid",
    "Tour V6 Shift",
    "Tour V6",
    "A1-Slope",
    "Tour V5 Shift",
    "Tour V5",
    "Pro XE",
    "Tour V4 Shift",
    "Tour V4",
    "Pro X2",
    "Tour V3"
  ],
  "Garmin": [
    "Approach Z82",
    "Approach Z80"
  ],
  "Voice Caddie": [
    "SL3",
    "SL2",
    "L5",
    "CL2"
  ],
  "Precision Pro": [
    "NX10",
    "NX9 Slope",
    "NX9",
    "NX7 Pro Slope"
  ],
  "Blue Tees": [
    "Series 3 Max",
    "Series 3",
    "Series 2 Pro+",
    "Series 2"
  ],
  "Leupold": [
    "GX-5i3",
    "GX-5c",
    "GX-3i3",
    "GX-2i3"
  ],
  "Nikon": [
    "Coolshot Pro II Stabilized",
    "Coolshot ProII",
    "Coolshot 50i",
    "Coolshot 20i GII",
    "Coolshot 20 GII"
  ],
  "Shot Scope": [
    "Pro LX+",
    "Pro L2",
    "Pro L1"
  ],
  "TecTecTec": [
    "ULT-X",
    "VPRO500",
    "VPRO500 Slope"
  ],
  "Callaway": [
    "Pro XS",
    "300 Pro Slope",
    "Micro Pro"
  ]
};
const LAUNCH_MONITORS: Record<string, string[]> = {
  "TrackMan": [
    "TrackMan 4",
    "TrackMan iO",
    "TrackMan Range"
  ],
  "Bushnell": [
    "Launch Pro"
  ],
  "FlightScope": [
    "X3",
    "Mevo+",
    "Mevo+ Pro Package",
    "Mevo"
  ],
  "Garmin": [
    "Approach R50",
    "Approach R10"
  ],
  "SkyTrak": [
    "SkyTrak+",
    "SkyTrak"
  ],
  "Rapsodo": [
    "MLM2PRO",
    "MLM"
  ],
  "Voice Caddie": [
    "SC4",
    "SC4 Pro",
    "SC300i"
  ],
  "Full Swing": [
    "KIT",
    "Pro Series"
  ],
  "Uneekor": [
    "EYE XO",
    "EYE MINI",
    "QED"
  ],
  "Swing Caddie": [
    "SC4",
    "SC300"
  ],
  "PRGR": [
    "HS-130A"
  ]
};
const GPS_DEVICES:   Record<string, string[]> = {
  "Garmin": [
    "Approach S70",
    "Approach S62",
    "Approach S42",
    "Approach S12",
    "Approach S60",
    "Approach S40",
    "Approach S20",
    "Approach S10",
    "Approach G80",
    "Approach Z82",
    "Approach G12",
    "Approach G10",
    "Approach S30",
    "Approach G30",
    "Approach CT10"
  ],
  "Shot Scope": [
    "V5",
    "V3",
    "H4",
    "PRO LX+",
    "PRO L2",
    "G4",
    "X5"
  ],
  "Bushnell": [
    "Phantom 2",
    "Phantom",
    "iON Edge",
    "iON2",
    "Wingman",
    "Wingman View",
    "Wingman Mini",
    "Phantom 3",
    "Excel",
    "Ion 2"
  ],
  "SkyCaddie": [
    "LX5",
    "LX5C",
    "SX500",
    "SX550"
  ],
  "TAG Heuer": [
    "Connected Calibre E4 Golf Edition (45mm)",
    "Connected Calibre E4 Golf Edition (42mm)"
  ],
  "GolfBuddy": [
    "aim W12",
    "aim W11",
    "aim W10",
    "Voice 2",
    "PT4 Lite",
    "Lite C",
    "aim L30"
  ],
  "Precision Pro": [
    "Nexus GPS Watch",
    "NX10 GPS Watch"
  ],
  "Callaway": [
    "Callaway Laser RCT (Rangefinder)",
    "Callaway 300 Pro Rangefinder"
  ],
  "Arccos": [
    "Arccos Caddie Smart Sensors (Gen 3)",
    "Arccos Caddie Smart Sensors (3rd Gen)",
    "Arccos Caddie Link"
  ],
  "Voice Caddie": [
    "T9",
    "SL2",
    "SL3",
    "T8",
    "SC200 Plus",
    "T6"
  ]
};
const TOWELS:        Record<string, string[]> = {
  "Titleist": [
    "Players Microfiber",
    "StaDry Performance",
    "Barrel Towel"
  ],
  "TaylorMade": [
    "Microfiber Cart Towel",
    "Tour Towel"
  ],
  "Callaway": [
    "Tri-Fold Towel",
    "Cotton Towel"
  ],
  "Ping": [
    "Players Towel",
    "Tour Towel"
  ],
  "Cobra": [
    "Microfiber Towel"
  ],
  "Club Glove": [
    "Microfiber Caddy Towel",
    "Tandem Towel"
  ],
  "Greens Towel": [
    "Microfiber"
  ],
  "Devant": [
    "Ultimate Microfiber",
    "Caddie Sport"
  ],
  "Maxfli": [
    "Microfiber Towel",
    "Cotton Tri-Fold"
  ],
  "FootJoy": [
    "FJ Towel"
  ]
};
const TEES:          Record<string, string[]> = {
  "Pride": [
    "Professional Tee System (PTS)",
    "Evolution",
    "Professional Tee System Plastic",
    "Bamboo",
    "ShortTee"
  ],
  "Zero Friction": [
    "Original 3-Prong",
    "Spectra"
  ],
  "Callaway": [
    "Par-Tee",
    "Bamboo Tees"
  ],
  "Titleist": [
    "Tee Pack"
  ],
  "Maxfli": [
    "Wood Tees"
  ],
  "Martini": [
    "Golf Tees",
    "Step-Up"
  ],
  "Brush-T": [
    "Original",
    "XL"
  ],
  "TaylorMade": [
    "Bamboo Tees"
  ],
  "Champ": [
    "Zarma FLYtee",
    "My Hite"
  ]
};

function withOther(list: string[] | undefined): string[] {
  if (!list || list.length === 0) return ['Other'];
  // dedupe + sort newest-first isn't possible without year metadata here.
  // Mobile sorts by year where possible; for our purposes we keep mobile's
  // array order (roughly newest-first) and just append "Other".
  return [...list, 'Other'];
}

/**
 * Resolve the list of models to display for a given category + subcategory +
 * brand. Always includes "Other" as the last option. Returns ["Other"] when
 * no models are available for that combination (the caller should then show
 * a free-text input instead of a dropdown).
 */
export function getModelsFor(
  category: string,
  subcategory: string | null | undefined,
  brand: string | null | undefined,
): string[] {
  if (!brand || brand === 'Other') return ['Other'];

  if (category === 'Clubs') {
    const sub = subcategory ?? '';
    return withOther(CLUBS[sub]?.[brand]);
  }

  if (category === 'Shafts, Grips & Heads') {
    if (subcategory === 'Shafts') return withOther(SHAFTS[brand]);
    if (subcategory === 'Grips')  return withOther(GRIPS[brand]);
    if (subcategory === 'Heads') {
      // Heads share club model lists — try driver/iron/etc. and use the first
      // non-empty list for this brand.
      const types = ['Drivers', 'Irons', 'Fairway Woods', 'Hybrids', 'Wedges', 'Putters'];
      for (const t of types) {
        const list = CLUBS[t]?.[brand];
        if (list && list.length) return withOther(list);
      }
      return ['Other'];
    }
    return ['Other'];
  }

  if (category === 'Balls') return withOther(BALLS[brand]);

  if (category === 'Clothing') {
    if (subcategory === 'Hats & Caps') return withOther(HATS[brand]);
    if (subcategory === 'Sunglasses')  return withOther(SUNGLASSES[brand]);
    if (subcategory === 'Gloves')      return withOther(GLOVES[brand]);
    return withOther(CLOTHING[brand]);
  }

  if (category === 'Shoes') return withOther(SHOES[brand]);

  if (category === 'Accessories') {
    if (subcategory === 'Bags')            return withOther(BAGS[brand]);
    if (subcategory === 'Headcovers')      return withOther(HEADCOVERS[brand]);
    if (subcategory === 'Rangefinders')    return withOther(RANGEFINDERS[brand]);
    if (subcategory === 'Launch Monitors') return withOther(LAUNCH_MONITORS[brand]);
    if (subcategory === 'GPS Devices')     return withOther(GPS_DEVICES[brand]);
    if (subcategory === 'Towels')          return withOther(TOWELS[brand]);
    if (subcategory === 'Tees')            return withOther(TEES[brand]);
    return ['Other'];
  }

  // Training Aids, Trolleys, Everything Else — mobile groups these by
  // product sub-type rather than brand, so we can't reliably resolve a
  // brand → models list. Fall back to free-text.
  return ['Other'];
}

/**
 * True when getModelsFor would return more than just "Other" — i.e. a
 * real dropdown is worth showing.
 */
export function hasModelsFor(
  category: string,
  subcategory: string | null | undefined,
  brand: string | null | undefined,
): boolean {
  const list = getModelsFor(category, subcategory, brand);
  return list.length > 1;
}
